/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CameraNodePanel: typeof import('./src/components/editor-segment/CameraNodePanel.vue')['default']
    EditorSegment: typeof import('./src/components/editor-segment/index.vue')['default']
    EditorToolbar: typeof import('./src/components/editor-segment/EditorToolbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFocusTrap: typeof import('element-plus/es')['ElFocusTrap']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOverlay: typeof import('element-plus/es')['ElOverlay']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    MotionNodePanel: typeof import('./src/components/editor-segment/MotionNodePanel.vue')['default']
    PauseNode: typeof import('./src/components/editor-segment/PauseNode.vue')['default']
    PauseTooltip: typeof import('./src/components/editor-segment/PauseTooltip.vue')['default']
    SegmentNode: typeof import('./src/components/editor-segment/SegmentNode.vue')['default']
    SpeakText: typeof import('./src/components/editor-segment/SpeakText.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    Test: typeof import('./src/components/test/index.vue')['default']
  }
}
