/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CameraNode: typeof import('./src/components/editor-segment/CameraNode.vue')['default']
    CameraNodePanel: typeof import('./src/components/editor-segment/CameraNodePanel.vue')['default']
    CameraNodePenal: typeof import('./src/components/editor-segment/CameraNodePenal.vue')['default']
    EditorSegment: typeof import('./src/components/editor-segment/index.vue')['default']
    EditorToolbar: typeof import('./src/components/editor-segment/EditorToolbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    MotionNode: typeof import('./src/components/editor-segment/MotionNode.vue')['default']
    MotionNodePanel: typeof import('./src/components/editor-segment/MotionNodePanel.vue')['default']
    PauseNode: typeof import('./src/components/editor-segment/PauseNode.vue')['default']
    PauseTooltip: typeof import('./src/components/editor-segment/PauseTooltip.vue')['default']
    SegmentNode: typeof import('./src/components/editor-segment/SegmentNode.vue')['default']
    SegmentNodePanel: typeof import('./src/components/editor-segment/SegmentNodePanel.vue')['default']
    SegmentNodePannel: typeof import('./src/components/editor-segment/SegmentNodePannel.vue')['default']
    SpeakNode: typeof import('./src/components/editor-segment/SpeakNode.vue')['default']
    SpeakText: typeof import('./src/components/editor-segment/SpeakText.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    Test: typeof import('./src/components/editor-segment/test.vue')['default']
    TestInput: typeof import('./src/components/editor-segment/TestInput.vue')['default']
    Toolbar: typeof import('./src/components/editor-segment/Toolbar.vue')['default']
  }
}
