import { createApp } from 'vue';
import './style.css';
import App from './App.vue';
import 'virtual:svg-icons-register';
import SvgIcon from './components/svg-icon/index.vue';
import 'element-plus/es/components/message/style/css';
import { createPinia } from 'pinia';
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
app.component('SvgIcon', SvgIcon);
app.mount('#app');
